### ISSUE TITLE
Env YAML file

### ISSUE THREAD

**Issue by alpinedev51** [NBAtrev/UFC-Elo-Engine#4]
Make an environment.yml file for consistent environments for users, devs, and deploying in a cloud environment.

- Make sure the environment is as minimal as possible. If you use conda to create the file, lots of times there will be circular dependencies and unused packages. Use something to check dependencies and test env creation locally before pushing the YAML file.

**Comment by abarton51** [comment]
https://github.com/NBAtrev/UFC-Elo-Engine/pull/5
